services:
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  test:
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    entrypoint: pytest -rP
    ports:
      - '8080:8080'
    depends_on:
      - redis
    environment:
      - RP_REDIS_HOST=redis
  